name: homework

on: push

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v2
      run: date
  windows:
    runs-on: windows-latest
    steps:
      uses: actions/checkout@v2
      run: Get-Date
  macos:
    runs-on: macos-latest
    steps:
      uses: actions/checkout@v2
      run: date
  depends:
    runs-on: ubuntu-latest
    needs: [job1, job2, job3]
    steps:
      uses: actions/checkout@v2
      run: echo 'Done'
